version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Running migrations..."
      - python manage.py migrate --noinput
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput
artifacts:
  files:
    - '**/*'
